FROM node:12-alpine

ENV TZ Asia/Seoul
WORKDIR /usr/src/app

COPY monitorworker/package*.json ./

RUN apk add tzdata
RUN npm install -g pm2 && npm install

COPY ./monitorworker/ .

CMD [ "npm", "start" ]
