FROM node:12-alpine

ENV TZ Asia/Seoul
WORKDIR /usr/src/app

COPY transferworker/package*.json ./

RUN apk add python3 tzdata make g++
RUN npm install

COPY ./transferworker/ .

CMD [ "npm", "start" ]
