FROM node:12-alpine

ENV TZ Asia/Seoul
WORKDIR /usr/src/app

COPY nodeserver/package*.json ./

RUN apk add tzdata
RUN npm install -g pm2 && npm install

COPY ./nodeserver/ .

EXPOSE 8080

CMD [ "npm", "start" ]
